# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ImGui_config = debug
  saffron_engine_2d_config = debug
  algorithms_config = debug

else ifeq ($(config),release)
  ImGui_config = release
  saffron_engine_2d_config = release
  algorithms_config = release

else ifeq ($(config),dist)
  ImGui_config = dist
  saffron_engine_2d_config = dist
  algorithms_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := ImGui saffron-engine-2d algorithms

.PHONY: all clean help $(PROJECTS) Engine Engine/deps

all: $(PROJECTS)

Engine: Engine/deps saffron-engine-2d

Engine/deps: ImGui

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C build -f ImGui.make config=$(ImGui_config)
endif

saffron-engine-2d: ImGui
ifneq (,$(saffron_engine_2d_config))
	@echo "==== Building saffron-engine-2d ($(saffron_engine_2d_config)) ===="
	@${MAKE} --no-print-directory -C build -f saffron-engine-2d.make config=$(saffron_engine_2d_config)
endif

algorithms: saffron-engine-2d ImGui
ifneq (,$(algorithms_config))
	@echo "==== Building algorithms ($(algorithms_config)) ===="
	@${MAKE} --no-print-directory -C build -f algorithms.make config=$(algorithms_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f ImGui.make clean
	@${MAKE} --no-print-directory -C build -f saffron-engine-2d.make clean
	@${MAKE} --no-print-directory -C build -f algorithms.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ImGui"
	@echo "   saffron-engine-2d"
	@echo "   algorithms"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"